FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --legacy-peer-deps
COPY . .
ARG VITE_API_URL
ARG VITE_SENSOR_URL
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_SENSOR_URL=$VITE_SENSOR_URL
RUN npm run build

FROM nginx:alpine AS final
RUN apk add --no-cache curl
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]